# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafikler.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui
import pyqtgraph

class Grafik(object):
    def setupUi(self, Form):
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 590, 1200, 210))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(9)
        font.setFamily('Courier New')

        styles = {'color': 'green', 'font-size': '11pt', 'font-weight': 'bold'}
        self.Temp = pyqtgraph.PlotWidget(self.horizontalLayoutWidget, font = font)
        self.Temp.setObjectName("widget_3")
        self.Temp.setBackground("transparent")
        self.Temp.setTitle("Sıcaklık", **styles)
        self.Temp.setLabel('left',  '°C', **styles)
        item = self.Temp.getPlotItem()
        item.getAxis("bottom").setTickFont(font)
        item.getAxis("left").setTickFont(font)
        item.titleLabel.item.setFont(font)
        item.getAxis('left').setFont(font)
        item.getAxis('left').setTickFont(font)

        #self.Temp.setXRange(0, 100, padding=0)
        #self.Temp.setYRange(20,30)
        self.Temp_pen = pyqtgraph.mkPen(color=(0, 255, 0), width=4)
        self.horizontalLayout_2.addWidget(self.Temp)

        self.Pressure = pyqtgraph.PlotWidget(self.horizontalLayoutWidget, font = font)
        self.Pressure.setObjectName("widget_5")
        self.Pressure.setBackground("transparent")
        self.Pressure.setTitle("Basınç", **styles)
        self.Pressure.setLabel('left',  'mbar', **styles)
        item = self.Pressure.getPlotItem()
        item.getAxis("bottom").setTickFont(font)
        item.getAxis("left").setTickFont(font)
        item.titleLabel.item.setFont(font)
        item.getAxis('left').setFont(font)
        item.getAxis('bottom').setTickFont(font)

        #self.Pressure.setXRange(0, 100, padding=0)
        self.horizontalLayout_2.addWidget(self.Pressure)

        self.Velocity = pyqtgraph.PlotWidget(self.horizontalLayoutWidget)
        self.Velocity.setObjectName("widget_4")
        self.Velocity.setBackground("transparent")
        self.Velocity.setTitle("Hız", **styles)
        self.Velocity.setLabel('left',  'm/s', **styles)
        item = self.Velocity.getPlotItem()
        item.getAxis("bottom").setTickFont(font)
        item.getAxis("left").setTickFont(font)
        item.titleLabel.item.setFont(font)
        item.getAxis('left').setFont(font)

        #self.Velocity.setXRange(0, 100, padding=0)
        self.horizontalLayout_2.addWidget(self.Velocity)

        self.Altitude = pyqtgraph.PlotWidget(self.horizontalLayoutWidget)
        self.Altitude.setObjectName("widget_2")
        self.Altitude.setBackground("transparent")
        self.Altitude.setTitle("İrtifa", color="green")
        self.Altitude.setLabel('left',  'm', **styles)
        item = self.Altitude.getPlotItem()
        item.getAxis("bottom").setTickFont(font)
        item.getAxis("left").setTickFont(font)
        item.titleLabel.item.setFont(font)
        item.getAxis('left').setFont(font)

        #self.Altitude.setXRange(0, 100, padding=0)
        self.horizontalLayout_2.addWidget(self.Altitude)

        self.Altitude_Difference = pyqtgraph.PlotWidget(self.horizontalLayoutWidget)
        self.Altitude_Difference.setObjectName("widget")
        self.Altitude_Difference.setBackground("transparent")
        self.Altitude_Difference.setTitle("İrtifa Farkı", color="green")
        self.Altitude_Difference.setLabel('left', 'm', **styles)
        item = self.Altitude_Difference.getPlotItem()
        item.getAxis("bottom").setTickFont(font)
        item.getAxis("left").setTickFont(font)
        item.titleLabel.item.setFont(font)
        item.getAxis('left').setFont(font)

        #self.Altitude_Difference.setXRange(0, 100, padding=0)
        self.horizontalLayout_2.addWidget(self.Altitude_Difference)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate

from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Grafik()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
