# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gps.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Gps(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(324, 170)
        Form.setStyleSheet("background-color:rgbrgb(238, 236, 210);\n"
"color:rgb(80, 80, 80),;\n"
"font: 9pt \"Arial Rounded MT Bold\";\n"
"text-align:center;")
        self.Gps = QtWidgets.QFrame(Form)
        self.Gps.setGeometry(QtCore.QRect(30, 30, 281, 111))
        self.Gps.setStyleSheet("")
        self.Gps.setFrameShape(QtWidgets.QFrame.Panel)
        self.Gps.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Gps.setLineWidth(3)
        self.Gps.setMidLineWidth(1)
        self.Gps.setObjectName("Gps")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Gps)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.Gps)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.Gps)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.Gps)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.Gps)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.Gps)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.Gps)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.Gps)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.Gps)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.Gps)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.Gps)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.Gps)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.Gps)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label_7.setBuddy(self.Gps)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "GPS1 Lat."))
        self.label_3.setText(_translate("Form", "GPS1 Long."))
        self.label.setText(_translate("Form", "GPS1 Alt."))
        self.label_2.setText(_translate("Form", "42.3424"))
        self.label_4.setText(_translate("Form", "32.525"))
        self.label_6.setText(_translate("Form", "230"))
        self.label_7.setText(_translate("Form", "GPS2 Lat."))
        self.label_8.setText(_translate("Form", "GPS2 Long."))
        self.label_9.setText(_translate("Form", "GPS2 Alt."))
        self.label_10.setText(_translate("Form", "42.3424"))
        self.label_11.setText(_translate("Form", "32.525"))
        self.label_12.setText(_translate("Form", "230"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
